export const BANK_OF_ENGLAND_BASE_RATE = 0.0375;
export const BANK_OF_ENGLAND_BASE_RATE_PERCENT = 3.75;
export const BANK_OF_ENGLAND_RATE_LAST_UPDATED = "April 2026";

export const STATUTORY_INTEREST_ADDITION = 0.08;
export const STATUTORY_INTEREST_RATE =
  BANK_OF_ENGLAND_BASE_RATE + STATUTORY_INTEREST_ADDITION;
export const STATUTORY_INTEREST_RATE_PERCENT = 11.75;

export const FIXED_COMPENSATION_LOW = 40;
export const FIXED_COMPENSATION_MID = 70;
export const FIXED_COMPENSATION_HIGH = 100;
